CREATE TABLE ugyfel (
    ugyfel_azonosito  GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ugyfel_tipus       VARCHAR2(20) NOT NULL,
    orszag             VARCHAR2(50),
    eves_jovedelem     INTEGER,
    PRIMARY KEY ( ugyfel_azonosito ),
    CONSTRAINT check_ugyfel_tipus CHECK ( ugyfel_tipus IN (
        'LAKOSSAGI',
        'KISVALLALATI',
        'NAGYVALLALATI'
    ) )
);

CREATE TABLE rendeles(
    rendeles_azonosito  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ugyfel_azonosito NUMBER,
    rendeles_idopontja DATE NOT NULL,
    PRIMARY KEY (rendeles_azonosito),
    CONSTRAINT fk_ugyfel_azonosito 
    FOREIGN KEY (ugyfel_azonosito) REFERENCES ugyfel(ugyfel_azonosito),
    CONSTRAINT uq_egy_rendeles_egy_adott_idopontban UNIQUE(ugyfel_azonosito, rendeles_idopontja)
);