INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (1,'NAGYVALLALATI','NULL', NULL);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (2,'LAKOSSAGI','Dánia', NULL);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (3,'NAGYVALLALATI',NULL, NULL);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (4,'LAKOSSAGI',' magyarország', 525000);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (5,'NAGYVALLALATI',' magyarország', NULL);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (6,'NAGYVALLALATI',' magyarország', NULL);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (7,'NAGYVALLALATI',NULL, NULL);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (8,'KISVALLALATI','magyarorszag', 12500000);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (9,'NAGYVALLALATI','Magyarorszag', 15000000);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (10,'NAGYVALLALATI',' magyarország', NULL);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (11,'LAKOSSAGI',' Belgium', 17500000);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (12,'NAGYVALLALATI',' magyarország', NULL);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (13,'KISVALLALATI','Magyarország', 17500000);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (14,'NAGYVALLALATI','Magyar ország', 15555000);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (15,'NAGYVALLALATI',' magyarország ', 33126000);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (16,'LAKOSSAGI',' m agyarország', 33500000);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (17,'NAGYVALLALATI',' magyarorszÁg', NULL);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (18,'KISVALLALATI',NULL, NULL);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (19,'NAGYVALLALATI',NULL, NULL);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (20,'NAGYVALLALATI',NULL, NULL);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (21,'NAGYVALLALATI',' magyarorszÁg', NULL);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (22,'KISVALLALATI',' magyarország', NULL);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (23,'LAKOSSAGI',' magyarország', NULL);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (24,'NAGYVALLALATI',NULL, NULL);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (25,'NAGYVALLALATI',' magyarország', NULL);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (26,'NAGYVALLALATI','Ausztria', 19000000);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (27,'NAGYVALLALATI',' magyarország', NULL);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (28,'NAGYVALLALATI',' magyarország', 73500000);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (29,'KISVALLALATI',' magyarország', 23500000);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (30,'LAKOSSAGI', ' magyarország', 3350000);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (31,'LAKOSSAGI', ' magyarország', 2350000);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (32,'KISVALLALATI', ' magyarország', 3750000);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (33,'NAGYVALLALATI', ' magyarország', 7350000);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (34,'LAKOSSAGI', ' magyarország', 2350000);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (35,'KISVALLALATI', ' magyarország', 3750000);
INSERT INTO ugyfel(ugyfel_azonosito, ugyfel_tipus, orszag, eves_jovedelem ) VALUES (36,'NAGYVALLALATI', ' magyarország', 7350000);